### ISSUE TITLE
Setup Unit Testing

### ISSUE THREAD

**Issue by raybesiga** [sparkplug/momoapi-android#2]
**Tasks**

- [ ] setup testing suite
- [ ] add unit tests for collections, disbursements, remittances
- [ ] add unit tests for users
